version: '3'
services:
  app:
    container_name: "practice-three-vrm-app"
    build: ./build/app/
    volumes:
      - ./app:/app
    env_file:
      - ./build/app/.node_env
    ports:
    - 3000:3000
    tty: true
    init: true